### ISSUE TITLE
ubuntu18.04下可以正常安装但无法打开使用

### ISSUE THREAD

**Issue by xiezht** [innoob/netease-cloud-music#1]
rt.
系统版本为Ubuntu 18.04.1 LTS
下载release包直接使用Ubuntu Software打开。显示了install进度条，但无法正常打开界面。

**Comment by innoob** [comment]
尝试多次无法重现你说的情况，都能正常打开。你是指ubuntu软件里面没有“启动”按钮嘛？

**Comment by xiezht** [comment]
@innoob 
谢谢答复。我安装后有软件的图标，但点击图标之后了没有弹出相应的界面（确认重启过系统）。
实际上就和安装了网易云的官方版本情况一样，都打不开。
后来我使用了知乎上这个问题的最高赞的方法解决了：https://www.zhihu.com/question/277330447

**Comment by innoob** [comment]
我知道是怎么回事了，你在安装之前没有卸载官方的客户端，如果安装之前打开过官方客户端，会有残留一个关不掉的netease-cloud-music进程，这时候就要重启了。
怎么解决：把官方的客户端重新安装再卸载，重启之后再安装这个客户端。

**Comment by xiezht** [comment]
Good
