### ISSUE TITLE
rebuild.release-2版本在Ubuntu 18.04上修改配置后无法打开

### ISSUE THREAD

**Issue by bjraxk** [innoob/netease-cloud-music#9]
Version：netease-cloud-music_1.1.1+rebuild.release-2_amd64.deb（最新的版本）
OS：elementary OS 5.0 Juno（基于 Ubuntu 18.04 LTS 构建，Linux 4.15.0-45-generic，GTK+ 版本：3.22.30）
问题描述：dpkg安装后成功打开、登录网易账号并运行程序。在程序设置界面，修改下载位置（从默认的“用户名文件夹/音乐/CloudMusic/”修改为“用户名文件夹/音乐/”）后，程序闪退。
尝试解决：删除程序清理缓存并重启电脑，dpkg重装问题依旧，特此反馈。

**Comment by innoob** [comment]
如果出现这种情况，按道理安装官方原版的客户端是可以正常使用的。

**Comment by innoob** [comment]
已经复现这个情况了，安装官方版的客户端是可以正常使用的。

**Comment by bjraxk** [comment]
> 已经复现这个情况了，安装官方版的客户端是可以正常使用的。

亲测，官方客户端会闪退，无法使用。
